exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# إيقاف jekyll-feed عشان يوقف الـ bug
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  # جيكل-فيد موقوف عمدًا عشان github-pages 232

# إعدادات الثيم
theme: jekyll-theme-cayman
title: Fadi T. Elhersh 
description: Computer Science Instructor 
